name: pre-commit
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: terraform-linters/setup-tflint@v1
      with:
        tflint_version: latest
